include = [
    "app",
    "tests"
]

line-length = 88
indent-width = 4
target-version = "py312"

[lint]
ignore = []

fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
